### ISSUE TITLE
Error when `excludeFolders` in not specified

### ISSUE THREAD

**Issue by chris-j-major** [rioj7/commandOnAllFiles#5]
When running a command without `exclideFolders` being specified I get the following error:
```
2023-11-14 11:23:51.129 [error] TypeError: getConfigProperty(...).concat is not a function
	at /home/node/.vscode-server/extensions/rioj7.commandonallfiles-0.3.3/extension.js:107:64
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async i.h (/vscode/vscode-server/bin/linux-x64/d037ac076cee195194f93ce6fe2bdfe2969cc82d/out/vs/workbench/api/node/extensionHostProcess.js:125:139661) commandOnAllFiles.applyOnWorkspace {"value":"rioj7.commandOnAllFiles","_lower":"rioj7.commandonallfiles"}
```

**Comment by chris-j-major** [comment]
Actually, the problem was with my config, I'd added:
```
    "commandOnAllFiles.excludeFolders": {},
```
by mistake.
